[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/eliahilse/kyora"
rust-version = "1.88"
publish = false

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time"] }
tokio-util = "0.7"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
reqwest = { version = "0.12.28", default-features = false, features = ["rustls-tls", "json", "stream"] }
async-stream = "0.3"
tracing = "0.1"
wiremock = "0.6"
kyora-protocol = { path = "crates/protocol" }
kyora-providers = { path = "crates/providers" }

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
