[package]
name = "kyora-providers"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
futures.workspace = true
kyora-protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio-util.workspace = true
tokio.workspace = true
reqwest.workspace = true
http-body = "1"
async-stream.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["net", "io-util"] }
wiremock.workspace = true
tower = { version = "0.5", features = ["util"] }

[lints]
workspace = true
